'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');const fsp=fs.promises;
const {parseManifest,unpack}=require('./reference-cache.cjs');const {verifyAuthority,verifyAuthoritySync}=require('./destination-authority.cjs');const owned=require('./owned-cleanup.cjs');
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');const sha=/^[a-f0-9]{64}$/;const rev=/^[a-f0-9]{40}$/;
function errorText(e){try{const m=e&&e.message;return typeof m==='string'?m.slice(0,4096):'Uncapturable error';}catch(_){return 'Uncapturable error';}}
function check(ok,m){if(!ok)throw new Error(m);}
function shape(v,n){check(v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).sort().join('|')===n.sort().join('|'),'Multipart schema mismatch');}
function parseIndex(bytes,pin){
 check(Buffer.isBuffer(bytes)&&bytes.length<=1024*1024&&sha.test(pin)&&hash(bytes)===pin,'Multipart index checksum/size');const value=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes));check(Buffer.from(JSON.stringify(value)).equals(bytes),'Multipart index canonical JSON');shape(value,['version','sourceRevision','toolRevision','sourceRelativePrefix','memberSetSHA256','memberIntents','parts']);check(value.version===1&&rev.test(value.sourceRevision)&&rev.test(value.toolRevision)&&sha.test(value.memberSetSHA256),'Multipart revision/hash');check(value.sourceRelativePrefix==='examples/figma-plugin/holistic/assets','Unexpected source-relative reference prefix');check(Array.isArray(value.parts)&&value.parts.length>0&&value.parts.length<=128,'Multipart count');
 check(Array.isArray(value.memberIntents)&&value.memberIntents.length>0&&value.memberIntents.length<=10000,'Member intent count');const intents=new Map();for(const intent of value.memberIntents){shape(intent,['path','kind','executionAllowed']);check(typeof intent.path==='string'&&!intents.has(intent.path)&&(intent.kind==='data'||intent.kind==='historical-code-proof')&&intent.executionAllowed===false,'Invalid/duplicate executable reference intent');intents.set(intent.path,intent.kind);}
 const records=[],manifests=[],paths=new Set(),partPins=new Set();
 for(const part of value.parts){shape(part,['manifestSHA256','manifestJSON']);check(typeof part.manifestJSON==='string'&&sha.test(part.manifestSHA256)&&!partPins.has(part.manifestSHA256),'Duplicate/bad part descriptor');partPins.add(part.manifestSHA256);const m=parseManifest(Buffer.from(part.manifestJSON),part.manifestSHA256);check(m.sourceRevision===value.sourceRevision&&m.toolRevision===value.toolRevision,'Cross-part revision drift');
 for(const e of m.members){check(e.path.startsWith(value.sourceRelativePrefix+'/'),'Member outside source-reference prefix');const lower=e.path.toLowerCase();check(!paths.has(lower),'Duplicate/case collision across parts');paths.add(lower);check(intents.has(e.path),'Missing reference intent');records.push({path:e.path,bytes:e.bytes,sha256:e.sha256,kind:intents.get(e.path),executionAllowed:false});}manifests.push({pin:part.manifestSHA256,manifest:m});}
 records.sort((a,b)=>a.path<b.path?-1:a.path>b.path?1:0);for(const e of records){const segments=e.path.split('/');for(let i=1;i<segments.length;i++)check(!paths.has(segments.slice(0,i).join('/').toLowerCase()),'Cross-part file/directory collision');}
 check(records.length===intents.size,'Unmatched reference intent');check(hash(Buffer.from(JSON.stringify(records)))===value.memberSetSHA256,'Whole member-set checksum');check(records.length<=10000,'Whole member count bound');return {index:value,manifests,records};
}
async function admitMultipart(indexBytes,indexSHA256,authority,getArchive){
 const journal={attemptedPaths:[],createdPaths:[],cleanupErrors:[],attemptedPartSHA256:[],validatedPartSHA256:[]};let stage,stageIdentity,reservationIdentity;const ownership=[];let admitted=false;
 function locations(){verifyAuthoritySync(authority);for(const e of [stageIdentity,reservationIdentity].filter(Boolean))owned.assertTree(e,ownership);}
 async function fence(){await verifyAuthority(authority);locations();}
 function wholeBytes(root,records){locations();for(const e of records){const p=path.join(root,e.path),expected=ownership.find(x=>x.path===p);check(expected&&expected.type==='file','Whole member ownership absent');const fd=fs.openSync(p,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);try{const s=fs.fstatSync(fd);check(s.isFile()&&s.dev===expected.dev&&s.ino===expected.ino&&s.size===e.bytes,'Whole member current identity/size');check(hash(fs.readFileSync(fd))===e.sha256,'Whole member current SHA256');}finally{fs.closeSync(fd);}}locations();}
 try{
 const parsed=parseIndex(indexBytes,indexSHA256);check(typeof getArchive==='function','Trusted part-byte provider required');const cacheRoot=await verifyAuthority(authority);locations();stage=await fsp.mkdtemp(path.join(cacheRoot,'.multipart-stage-'));journal.createdPaths.push(stage);stageIdentity=owned.capture(stage);ownership.push(stageIdentity);await fsp.chmod(stage,0o700);locations();
 for(const part of parsed.manifests){await fence();journal.attemptedPartSHA256.push(part.pin);const archive=await getArchive(Object.freeze({manifestSHA256:part.pin,url:part.manifest.archive.url,bytes:part.manifest.archive.bytes,sha256:part.manifest.archive.sha256}));await fence();const entries=unpack(archive,part.manifest);
 for(const {entry,bytes} of entries){await fence();let dir=stage;for(const segment of entry.path.split('/').slice(0,-1)){dir=path.join(dir,segment);try{const s=await fsp.lstat(dir);check(s.isDirectory()&&!s.isSymbolicLink(),'Multipart parent not directory');}catch(e){if(e.code!=='ENOENT')throw e;await fence();journal.attemptedPaths.push(dir);await fsp.mkdir(dir,{mode:0o700});journal.createdPaths.push(dir);ownership.push(owned.capture(dir));}}
 const target=path.join(stage,entry.path);await fence();journal.attemptedPaths.push(target);const h=await fsp.open(target,fs.constants.O_WRONLY|fs.constants.O_CREAT|fs.constants.O_EXCL|fs.constants.O_NOFOLLOW,0o600);journal.createdPaths.push(target);ownership.push(owned.captureHandle(h.fd,target));try{await fence();await h.writeFile(bytes);await h.sync();}finally{await h.close();}locations();check(hash(await fsp.readFile(target))===entry.sha256,'Multipart staged member readback');await fence();}
 journal.validatedPartSHA256.push(part.pin);
 }
 await fence();check(journal.validatedPartSHA256.length===parsed.manifests.length,'Incomplete part set');for(const e of parsed.records){check(hash(await fsp.readFile(path.join(stage,e.path)))===e.sha256,'Whole staged member checksum');await fence();}
 const dest=path.join(cacheRoot,'reference-bundle-'+indexSHA256);journal.attemptedPaths.push(dest);await fence();await fsp.mkdir(dest,{mode:0o700});journal.createdPaths.push(dest);reservationIdentity=owned.capture(dest);ownership.push(reservationIdentity);await fence();const content=path.join(dest,'files'),oldStage=stage;await fsp.rename(stage,content);for(const e of ownership)if(e.path===oldStage||e.path.startsWith(oldStage+path.sep))e.path=content+e.path.slice(oldStage.length);stage=undefined;stageIdentity=undefined;journal.createdPaths.push(content);await fence();
 const pending=path.join(dest,'.bundle-admission-pending'),marker=path.join(dest,'admitted.json');const markerBytes=Buffer.from(JSON.stringify({version:1,indexSHA256,memberSetSHA256:parsed.index.memberSetSHA256,sourceRevision:parsed.index.sourceRevision,toolRevision:parsed.index.toolRevision,members:parsed.records.length,partManifestSHA256:journal.validatedPartSHA256}));journal.attemptedPaths.push(pending);const h=await fsp.open(pending,fs.constants.O_WRONLY|fs.constants.O_CREAT|fs.constants.O_EXCL|fs.constants.O_NOFOLLOW,0o600);journal.createdPaths.push(pending);ownership.push(owned.captureHandle(h.fd,pending));try{await fence();await h.writeFile(markerBytes);await h.sync();}finally{await h.close();}await fence();check(fs.readFileSync(pending).equals(markerBytes),'Whole marker bytes drift');wholeBytes(content,parsed.records);fs.renameSync(pending,marker);for(const e of ownership)if(e.path===pending)e.path=marker;admitted=true;journal.createdPaths.push(marker);await fence();wholeBytes(content,parsed.records);check(fs.readFileSync(marker).equals(markerBytes),'Final whole marker bytes drift');locations();
 return {ok:true,admitted:true,indexSHA256,referenceRoot:content,members:parsed.records.length,parts:parsed.manifests.length,journal};
 }catch(error){if(!admitted)for(const identity of [stageIdentity,reservationIdentity].filter(Boolean))try{await verifyAuthority(authority);owned.remove(identity,ownership,()=>verifyAuthoritySync(authority));}catch(clean){journal.cleanupErrors.push({path:identity.path,error:errorText(clean)});}return {ok:false,admitted,error:errorText(error),indexSHA256,journal};}
}
module.exports={parseIndex,admitMultipart};
